### ISSUE TITLE
go error highlighting should be disabled by default

### ISSUE THREAD

**Issue by nhooyr** [google/vim-ft-go#2] opened 2017-01-04 13:25 UTC
I find it incredibly annoying that it keeps highlighting things as errors as I am typing. It doesn't make much sense and it isn't very useful.

https://github.com/vim/vim/blob/master/runtime/syntax/go.vim#L31-L45

It should be disabled by default. It isn't something vim normally does for any other language, it's usually deferred to a plugin.

Watch https://asciinema.org/a/1pakyg673na373820djkl0b1q for what I mean

**Comment by xanderman** [comment] 2017-01-04 15:01
The one that's shown in the screencast is specifically trailing whitespace. You can turn it off easily by putting 'let g:go_highlight_trailing_whitespace_error = 1' in your vimrc.

Given the extremely opinionated nature of go style and formatting, I believe it is appropriate to enable this error highlighting by default. However, having it highlight as you type is really annoying. I understand it is possible to have the regex do a negative look-ahead for the cursor (though it might be slow?). I'm not good enough with vim regex to set it up, though.

**Comment by nhooyr** [comment] 2017-01-04 15:04
But users can just run gofmt and forget about manually fixing these formatting errors. What's the point?

**Comment by Kashomon** [comment] 2017-01-04 15:15
As someone who codes in Go everyday, I'm inclined to agreed with @nhooyr. The style guide is really: run go fmt.

Let's set this default to 0.

**Comment by xanderman** [comment] 2017-01-04 15:35
As someone who only occasionally codes in Go, I'm not inclined to argue. Send a pull request and I'll merge it. (Or wait a while and I'll get around to it.) I'm not entirely sure what the process is for getting changes made here merged into vim, but at least I know who to ask.

**Closed** 2017-01-04 15:40 UTC

**Comment by dezza** [comment] 2017-02-28 15:35
And even if you have a shiftwidth of 8 like gofmt uses it still shows this error highlight. What is the reasoning for this? I have no idea if I should report/issue it here, in vim-go or in the vim repo itself. It just seems illogical.

**Comment by nhooyr** [comment] 2017-02-28 15:49
gofmt doesn't have a shiftwidth of 8, it doesn't have a shiftwidth at all. It just uses tabs. I don't understand what the problem is.

Also, vim-go was changed in #1167

**Comment by dezza** [comment] 2017-02-28 15:52
Ah. I see. So the reason why it shows the highlight is actually because it expects tabs.

**Comment by dbarnett** [comment] 2017-02-28 17:05
> And even if you have a shiftwidth of 8 like gofmt uses it still shows this error highlight by `g:go_highlight_trailing_whitespace_error`.

Are we still talking about trailing whitespace? I don't follow what shiftwidth has to do with that.

**Comment by dbarnett** [comment] 2017-02-28 17:10
Looks like we fixed it here but still need to upstream the change into https://github.com/vim/vim/blob/master/runtime/syntax/go.vim.

**Comment by dezza** [comment] 2017-02-28 17:13
My shiftwidth assumption was wrong yes and I realized the vim repo is where it is still enabled. It would be nice if vim also had this. If someone could clarify what the original intention with this was that would be awesome. I haven't seen it in other ft-plugins.

**Comment by dbarnett** [comment] 2017-02-28 17:39
> I haven't seen it in other ft-plugins.

@dezza Right, go was apparently treated specially because the go authors and community are especially dogmatic about formatting. "go isn't like other filetypes" shouldn't be that surprising, the issue is that this "feature" is not that useful.
